apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cr-micro
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["delete", "create", "patch", "get", "list"]

- apiGroups: [""]
  resources: ["pods", "pods/portforward", "pods/log", "pods/exec"]
  verbs: ["get", "list", "create", "delete", "watch"]

- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create"]

- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "patch"]

- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "create", "delete"]

- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]

- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]

- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "patch"]

- apiGroups: ["apps", "extensions"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "update", "delete"]

- apiGroups: ["extensions"]
  resources: ["replicasets"]
  verbs: ["get", "list", "update", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: crb-micro
roleRef:
  kind: ClusterRole
  name: cr-micro
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: gc-micro-sa
  namespace: greencompute
